### ISSUE TITLE
cython is there but not found

### ISSUE THREAD

**Issue by mxa** [jack-mixer/jack_mixer#109]
On Kubuntu 20.10
I followed the [wiki](https://github.com/jack-mixer/jack_mixer/wiki/Installing-on-debian---Ubuntu) for 20.04

```
$ meson setup builddir --prefix=/usr --buildtype=release
The Meson build system
Version: 0.55.3
Source dir: /home/ipp/Code/jack_mixer
Build dir: /home/ipp/Code/jack_mixer/builddir
Build type: native build
Project name: jack_mixer
Project version: 15
C compiler for the host machine: cc (gcc 10.2.0 "cc (Ubuntu 10.2.0-13ubuntu1) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency glib-2.0 found: YES 2.66.1
Library m found: YES
Run-time dependency jack found: YES 1.9.14
Dependency jack found: YES 1.9.14 (cached)
Program python3 (gi, cairo, xdg) found: YES (/usr/bin/python3) modules: gi, cairo, xdg
Program cython found: NO

src/meson.build:47:8: ERROR: Problem encountered: The 'cython' program was not found but is required.
Please install Cython from: https://pypi.org/project/Cython/.

A full log can be found at /home/ipp/Code/jack_mixer/builddir/meson-logs/meson-log.txt
$ pip install cython
Requirement already satisfied: cython in /usr/lib/python3/dist-packages (0.29.21)


```

**Comment by SpotlightKid** [comment]
what does `which cython` say?

**Comment by SpotlightKid** [comment]
Also, can you please copy&paste `/home/ipp/Code/jack_mixer/builddir/meson-logs/meson-log.txt` here?

**Comment by mxa** [comment]
```
$ which cython
$ which cython3
/usr/bin/cython3
$ cython --version
Command 'cython' not found, did you mean:
  command 'cython3' from deb cython3 (0.29.21-1ubuntu1)
  command 'jython' from deb jython (2.7.2~b2+repack1-1ubuntu1)
Try: sudo apt install <deb name>
$ cython3 --version
Cython version 0.29.21

```

**Comment by mxa** [comment]
```
Build started at 2021-03-08T19:29:14.665314
Main binary: /usr/bin/python3
Build Options: -Dprefix=/usr -Dbuildtype=release
Python system: Linux
The Meson build system
Version: 0.55.3
Source dir: /home/ipp/Code/jack_mixer
Build dir: /home/ipp/Code/jack_mixer/builddir
Build type: native build
None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
Project name: jack_mixer
Project version: 15
None of 'CC' are defined in the environment, not changing global flags.
None of 'CFLAGS' are defined in the environment, not changing global flags.
None of 'LDFLAGS' are defined in the environment, not changing global flags.
None of 'CPPFLAGS' are defined in the environment, not changing global flags.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity check compiler command line: cc /home/ipp/Code/jack_mixer/builddir/meson-private/sanitycheckc.c -o /home/ipp/Code/jack_mixer/builddir/meson-private/sanitycheckc.exe -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/ipp/Code/jack_mixer/builddir/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (gcc 10.2.0 "cc (Ubuntu 10.2.0-13ubuntu1) 10.2.0")
C linker for the build machine: cc ld.bfd 2.35.1
None of 'AR' are defined in the environment, not changing global flags.
None of 'CC' are defined in the environment, not changing global flags.
None of 'CFLAGS' are defined in the environment, not changing global flags.
None of 'LDFLAGS' are defined in the environment, not changing global flags.
None of 'CPPFLAGS' are defined in the environment, not changing global flags.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity check compiler command line: cc /home/ipp/Code/jack_mixer/builddir/meson-private/sanitycheckc.c -o /home/ipp/Code/jack_mixer/builddir/meson-private/sanitycheckc.exe -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/ipp/Code/jack_mixer/builddir/meson-private/sanitycheckc.exe
C compiler for the host machine: cc (gcc 10.2.0 "cc (Ubuntu 10.2.0-13ubuntu1) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
None of 'AR' are defined in the environment, not changing global flags.
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Pkg-config binary for MachineChoice.HOST is not cached.
None of 'PKG_CONFIG' are defined in the environment, not changing global flags.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --modversion glib-2.0` -> 0
2.66.1
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --cflags glib-2.0` -> 0
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config glib-2.0 --libs` -> 0
-L/usr/lib/x86_64-linux-gnu -lglib-2.0
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config glib-2.0 --libs` -> 0
-L/usr/lib/x86_64-linux-gnu -lglib-2.0
None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
None of 'CC_LD' are defined in the environment, not changing global flags.
Running compile:
Working directory:  /home/ipp/Code/jack_mixer/builddir/meson-private/tmpx7exoju8
Command line:  cc /home/ipp/Code/jack_mixer/builddir/meson-private/tmpx7exoju8/testfile.c -o /home/ipp/Code/jack_mixer/builddir/meson-private/tmpx7exoju8/output.exe -pipe -D_FILE_OFFSET_BITS=64 -O0 

Code:
 #include<stdio.h>
        
        int main(void) {
            printf("%ld\n", (long)(sizeof(void *)));
            return 0;
        };
Compiler stdout:
 
Compiler stderr:
 
Program stdout:

8

Program stderr:


Running compile:
Working directory:  /home/ipp/Code/jack_mixer/builddir/meson-private/tmp4k6i1it2
Command line:  cc /home/ipp/Code/jack_mixer/builddir/meson-private/tmp4k6i1it2/testfile.c -o /home/ipp/Code/jack_mixer/builddir/meson-private/tmp4k6i1it2/output.obj -pipe -c -D_FILE_OFFSET_BITS=64 -O0 --print-search-dirs 

Code:
 
Compiler stdout:
 install: /usr/lib/gcc/x86_64-linux-gnu/10/
programs: =/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/bin/
libraries: =/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../../lib/:/lib/x86_64-linux-gnu/10/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/10/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/lib/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../:/lib/:/usr/lib/

Compiler stderr:
 
Run-time dependency glib-2.0 found: YES 2.66.1
None of 'CC_LD' are defined in the environment, not changing global flags.
Running compile:
Working directory:  /home/ipp/Code/jack_mixer/builddir/meson-private/tmp8jvusvnn
Command line:  cc /home/ipp/Code/jack_mixer/builddir/meson-private/tmp8jvusvnn/testfile.c -o /home/ipp/Code/jack_mixer/builddir/meson-private/tmp8jvusvnn/output.exe -pipe -D_FILE_OFFSET_BITS=64 -O0 -Wl,--start-group -lm -Wl,--end-group -Wl,--allow-shlib-undefined 

Code:
 int main(void) { return 0; }

Compiler stdout:
 
Compiler stderr:
 
Library m found: YES
Pkg-config binary for MachineChoice.HOST is cached.
Determining dependency 'jack' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --modversion jack` -> 0
1.9.14
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --cflags jack` -> 0

PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config jack --libs` -> 0
-L/usr/lib/x86_64-linux-gnu -ljack
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config jack --libs` -> 0
-L/usr/lib/x86_64-linux-gnu -ljack
None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
Run-time dependency jack found: YES 1.9.14
Dependency jack found: YES 1.9.14 (cached)
Program python3 (gi, cairo, xdg) found: YES (/usr/bin/python3) modules: gi, cairo, xdg
Program cython found: NO

src/meson.build:47:8: ERROR: Problem encountered: The 'cython' program was not found but is required.
Please install Cython from: https://pypi.org/project/Cython/.

```

**Comment by SpotlightKid** [comment]
You have Cython installed from the debian/Ubuntu package [cython3](https://packages.ubuntu.com/focal/cython3), which installs the `cython` program as `cython3` (in `/usr/bin`). Unfortunately the meson configuration did not account for that yet. I just pushed commit f99d81c, which should fix that.

So please update your git checkout with `git pull` or compile from the source distribution (see "Step 2 (alternative)" on the wiki page). For the latter you should not need Cython at all.

**Comment by mxa** [comment]
I did `git pull` but the cynthon error persisted. So I did `/usr/bin$ sudo ln -s cython3 cython` which made this error go away. I still had to resolve the undocumented dependency `rst2man` (package `rst2pdf`) before it compiled.

However:
```
$ jack_mixer
Traceback (most recent call last):
  File "/usr/local/bin/jack_mixer", line 40, in <module>
    import jack_mixer_c
ModuleNotFoundError: No module named 'jack_mixer_c'
```

**Comment by mxa** [comment]
>  I just pushed commit [f99d81c](https://github.com/jack-mixer/jack_mixer/commit/f99d81c551e2d465dbf452b08ee7e7e9c94f3ad6), which should fix that.

This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by SpotlightKid** [comment]
> This commit does not belong...

Sorry, I pushed to the wring remote. Now pushed properly to this repo.

> I still had to resolve the undocumented dependency rst2man (package rst2pdf) before it compiled.

`rst2man` should be in package `python3-docutuils`. If you didn't have that installed, you didn't follow the instructions properly (see Step 2).

**Comment by mxa** [comment]
Sorry, different machine.
